---
core:
  num_workers: 10
  raise_on_error: False

logging:
  enabled: False

inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "inventory-local/hosts.yaml"
    group_file: "inventory-local/groups.yaml"
    defaults_file: "inventory-local/defaults.yaml"